matrix:
  include:
    - langauge: node_js
      node_js:
        - "iojs"
        - "7"
      before_script:
        - cd assets
      script:
        - npx brunch build --production

    - language: elixir
      elixir: '1.6'
      otp_release: '20.3'
      before_script:
        - MIX_ENV=prod
      script:
        - mix local.rebar --force
        - mix local.hex --force
        - mix deps.get --only prod
        - mix compile
        - mix phx.digest

