version: '3.1'

services:
  db:
    restart: always
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - DB_USER="postgres"
      - DB_PASS="postgres"
      - DB_NAME="blog2_db_1"


  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

